name: Build Android APK

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kód
        uses: actions/checkout@v4

      - name: Nastavení Java JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Oprava Windows konců řádků (CRLF na LF)
        run: |
          echo "Čistím soubory od neviditelných Windows znaků..."
          find . -name "gradlew" -exec sed -i 's/\r$//' {} \;
          find . -name "gradlew" -exec chmod +x {} \;

      - name: Sestavení pomocí oficiální Gradle Action
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: assembleDebug

      - name: Nahrání hotového APK k dispozici ke stažení
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: |
            **/build/outputs/apk/debug/*.apk
